server:
  port: 8082

spring:
  application:
    name: config-service

  profiles:
    active: jdbc

  liquibase:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: root777
    change-log: classpath:db/db.changelog-master.yml
    enabled: true
    default-schema: config

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root777

  cloud:
    config:
      enabled: true
      fail-fast: true
      discovery:
        enabled: true
        service-id: configserver
      server:
        jdbc:
          sql: SELECT "key", "value" from config where APPLICATION=? and PROFILE=? and LABEL=?


eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

